[package]
name = "minify-html-onepass"
description = "Even faster version of minify-html"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories = ["compression", "development-tools::build-utils", "web-programming"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
ahash.workspace = true
aho-corasick.workspace = true
lightningcss.workspace = true
memchr.workspace = true
minify-html-common.workspace = true
once_cell.workspace = true
oxc_allocator.workspace = true
oxc_codegen.workspace = true
oxc_minifier.workspace = true
oxc_parser.workspace = true
oxc_span.workspace = true
