[package]
name = "minify-html-common"
description = "Common code and data for minify-html*"
version = "0.0.3"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
ahash.workspace = true
aho-corasick.workspace = true
once_cell.workspace = true

[build-dependencies]
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
